- name: Deploy Nginx and Monitoring Stack
  hosts: unixhosts
  become: yes
  vars:
    ECR_REPO_URL: "yelucpp/devops_workflow_integration_repo"
    NGINX_PORT: "8081"
    # Variables for Grafana authentication - to be passed as extra vars
    # GRAFANA_URL: "http://localhost:3000"
    # GRAFANA_USER: "admin"
    # GRAFANA_PASSWORD: "admin"
    
  tasks:
    - name: Install docker
      shell: sudo snap install docker

    # --- Monitoring Components Installation ---

    - name: Install community.grafana collection (Requires Ansible 2.9+)
      ansible.builtin.command: ansible-galaxy collection install community.grafana
      # This task might require a specific environment/prerequisites on the VM.
      # It's often run on the Ansible controller (localhost), but placed here for simplicity.
      # If the target host has Ansible installed, it can install collections.
      ignore_errors: yes 

    - name: Install Prometheus and Grafana (Example: using Docker containers)
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        published_ports: "{{ item.ports }}"
        volumes: "{{ item.volumes | default([]) }}"
        restart_policy: always
      loop:
        - name: prometheus
          image: prom/prometheus:latest
          ports: ["9090:9090"]
          volumes: 
            - /home/leon/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - name: grafana
          image: grafana/grafana:latest
          ports: ["3000:3000"]
          volumes: 
            # Mount the datasource configuration file
            - /home/leon/grafana/provisioning/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
            # Mount a persistent volume for Grafana data (optional but recommended)
            - grafana_data:/var/lib/grafana
          env:
            # Set initial admin password, often required for initial setup/API access
            GF_SECURITY_ADMIN_PASSWORD: "{{ GRAFANA_PASSWORD | default('admin') }}" 
            # To allow non-authenticated API requests for datasource provisioning (if not using API Key)
            GF_AUTH_ANONYMOUS_ENABLED: "true" 
            GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin" 

    # --- Prometheus and Grafana Configuration ---

    - name: Ensure configuration directories exist
      ansible.builtin.file:
        path: "/home/leon/{{ item }}"
        state: directory
        owner: leon
        group: leon
        mode: '0755'
      loop:
        - prometheus
        - grafana/provisioning/datasources

    - name: Copy prometheus.yml to VM
      ansible.builtin.copy:
        src: prometheus.yml
        dest: /home/leon/prometheus/prometheus.yml

    - name: Copy datasource.yml to VM
      ansible.builtin.copy:
        src: datasource.yml
        dest: /home/leon/grafana/provisioning/datasources/datasource.yml

    # --- Grafana Datasource Configuration (Alternative to file provisioning) ---
    
    # NOTE: File provisioning with datasource.yml (above) is the standard Grafana
    # way. If you prefer to use the Ansible module for control:
    # 
    # - name: Create Prometheus Data Source in Grafana
    #   community.grafana.grafana_datasource:
    #     name: Prometheus
    #     grafana_url: "{{ GRAFANA_URL | default('http://localhost:3000') }}"
    #     grafana_user: "{{ GRAFANA_USER | default('admin') }}"
    #     grafana_password: "{{ GRAFANA_PASSWORD | default('admin') }}"
    #     ds_type: prometheus
    #     url: http://localhost:9090
    #     is_default: yes
    #     state: present

    # --- Docker Nginx Deployment Tasks (Existing) ---

    - name: Stop and remove old container
      community.docker.docker_container:
        name: web-server
        state: absent

    - name: Remove an image
      community.docker.docker_image_remove:
        name: "{{ ECR_REPO_URL }}:latest"

    - name: Log into Docker Hub
      community.docker.docker_login:
        username: "{{ DOCKERHUB_USERNAME }}"
        password: "{{ DOCKERHUB_PASSWORD }}"

    - name: Pull latest image
      community.docker.docker_image_pull:
        name: "{{ ECR_REPO_URL }}:latest"

    - name: Deploy container
      community.docker.docker_container:
        name: web-server
        image: "{{ ECR_REPO_URL }}:latest"
        published_ports: "{{ NGINX_PORT }}:80"
        # Optional: Add network to allow containers to talk
        network_mode: host # Simplest way to expose ports and allow communication

    - name: Check if web server is responding
      ansible.builtin.uri:
        url: "http://localhost:{{ NGINX_PORT }}"
        status_code: 200
      register: http_check
      failed_when: false
      changed_when: false

    - name: Display web server status
      ansible.builtin.debug:
        msg: "Web server is {{ 'up' if http_check.status == 200 else 'down' }}"